//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.31 at 06:30:06 PM NZST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.thymeleaf.org/presentation/blog", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.thymeleaf.presentation.entities.blog;
